0. Start
1. Stop
2. Change Lane
3. Turn left
4. Turn Right
5. Speed Up
6. Speed Down
7. Chalo
8. Ruk jao
9. Lane badlo
10. Bayain Muro
11. Dayain Muro
12. Tez chalo
13. Ahista Chalo

# This notebook does following things
# 1. loads preprocessed same length audio files
# 2. Extracting audio time series and sampling rate from each audio
# 3. Using audio time series and sampling rate to extract mfccs
# 4. Splitting mfccs into train and test data
# 5. Developing two models Lstm and Bilstm


In [12]:
import librosa
audioLength=2.5
filesBasicPath='VoiceData/sameLengthCommands/'
audioFileLength=[]
audio_path_ahistaChalo=[]
audio_path_bayainMuro=[]
audio_path_chalo=[]
audio_path_changeLane=[]
audio_path_dayainMuro=[]
audio_path_laneBadlo=[]
audio_path_rukJao=[]
audio_path_speedDown=[]
audio_path_speedUp=[]
audio_path_start=[]
audio_path_stop=[]
audio_path_tezChalo=[]
audio_path_turnLeft=[]
audio_path_turnRight=[]
numberOfCommands=85
for i in range(1,numberOfCommands+1):
    if i!=39 and i!=66 and i!=83:
        if librosa.get_duration(filename=filesBasicPath+str(i)+'/ahista chalo.wav')<=audioLength:
            audio_path_ahistaChalo.append(filesBasicPath+str(i)+'/ahista chalo.wav')
            audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/ahista chalo.wav'))
    if i!=46 and i!=39:  
        if librosa.get_duration(filename=filesBasicPath+str(i)+'/bayain muro.wav')<=audioLength:
            audio_path_bayainMuro.append(filesBasicPath+str(i)+'/bayain muro.wav')
            audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/bayain muro.wav'))
    if i!=46 and i!=39:    
        if librosa.get_duration(filename=filesBasicPath+str(i)+'/chalo.wav')<=2.5:
            audio_path_chalo.append(filesBasicPath+str(i)+'/chalo.wav')
            audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/chalo.wav'))
    if i!=46 and i!=39:
        if librosa.get_duration(filename=filesBasicPath+str(i)+'/dayain muro.wav')<=audioLength:
            audio_path_dayainMuro.append(filesBasicPath+str(i)+'/dayain muro.wav')
            audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/dayain muro.wav'))
    if i!=27 and i!=62 and i!=39 and i!=74:
        if librosa.get_duration(filename=filesBasicPath+str(i)+'/ruk jao.wav')<=audioLength:
            audio_path_rukJao.append(filesBasicPath+str(i)+'/ruk jao.wav')
            audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/ruk jao.wav'))
    if i!=5 and i!=18 and i!=19 and i!=39 and i!=74 and i!=83:
        if librosa.get_duration(filename=filesBasicPath+str(i)+'/tez chalo.wav')<=audioLength:
            audio_path_tezChalo.append(filesBasicPath+str(i)+'/tez chalo.wav')
            audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/tez chalo.wav'))
    if i!=25 and i!=37 and i!=36 and i!=38 and i!=53 and i!=39:
        if librosa.get_duration(filename=filesBasicPath+str(i)+'/lane badlo.wav')<=audioLength:
            audio_path_laneBadlo.append(filesBasicPath+str(i)+'/lane badlo.wav')
            audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/lane badlo.wav'))
    if i!=36 and i!=38:  
        if librosa.get_duration(filename=filesBasicPath+str(i)+'/change lane.wav')<=audioLength:
            audio_path_changeLane.append(filesBasicPath+str(i)+'/change lane.wav')
            audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/change lane.wav'))
    if i!=46 and i!=51:
        if librosa.get_duration(filename=filesBasicPath+str(i)+'/speed down.wav')<=audioLength:
            audio_path_speedDown.append(filesBasicPath+str(i)+'/speed down.wav')
            audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/speed down.wav'))
    if i!=26:
        if librosa.get_duration(filename=filesBasicPath+str(i)+'/speed up.wav')<=audioLength:
            audio_path_speedUp.append(filesBasicPath+str(i)+'/speed up.wav')
            audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/speed up.wav'))
    if i!=10 and i!=38 and i!=39 and i!=43 and i!=44 and i!=55:
        if librosa.get_duration(filename=filesBasicPath+str(i)+'/start.wav')<=audioLength:
            audio_path_start.append(filesBasicPath+str(i)+'/start.wav')
            audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/start.wav'))
    if i!=10 and i!=36 and i!=43:
        if librosa.get_duration(filename=filesBasicPath+str(i)+'/stop.wav')<=audioLength:
            audio_path_stop.append(filesBasicPath+str(i)+'/stop.wav')
            audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/stop.wav'))
    if i!=36 and i!=38:
        if librosa.get_duration(filename=filesBasicPath+str(i)+'/turn left.wav')<=audioLength:
            audio_path_turnLeft.append(filesBasicPath+str(i)+'/turn left.wav')
            audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/turn left.wav'))
    if i!=38 and i!=10 and i!=74:
        if librosa.get_duration(filename=filesBasicPath+str(i)+'/turn right.wav')<=audioLength:
            audio_path_turnRight.append(filesBasicPath+str(i)+'/turn right.wav')
            audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/turn right.wav'))
print("Loading is completed Done")


Loading is completed Done


In [13]:
print(len(audioFileLength))#1146 files originally

1086


In [14]:
print(max(audioFileLength))
print(min(audioFileLength))

2.5
2.5


<h1>Following code is extracting</h1>
<h2>1. Audio time series</h2>
<h2>2. Sampling rate</h2>

In [17]:
count=1
x_ahistaChalo=[]
sr_ahistaChalo=[]
for i in range(0,len(audio_path_ahistaChalo)):
    x1,sr1=librosa.load(audio_path_ahistaChalo[i])
    x_ahistaChalo.append(x1)
    sr_ahistaChalo.append(sr1)
    count+=1
    
print(len(x_ahistaChalo))

74


In [18]:
count=1
x1=0
s1=0
x_bayainMuro=[]
sr_bayainMuro=[]
for i in range(0,len(audio_path_bayainMuro)):
    x1,sr1=librosa.load(audio_path_bayainMuro[i])
    x_bayainMuro.append(x1)
    sr_bayainMuro.append(sr1)
    count+=1
print(len(x_bayainMuro))

80


In [19]:
count=1
x_laneBadlo=[]
sr_laneBadlo=[]
for i in range(0,len(audio_path_laneBadlo)):
    x1,sr1=librosa.load(audio_path_laneBadlo[i])
    x_laneBadlo.append(x1)
    sr_laneBadlo.append(sr1)
    count+=1
print(len(x_laneBadlo))

70


In [20]:
count=1
x_changeLane=[]
sr_changeLane=[]
for i in range(0,len(audio_path_changeLane)):
    x1,sr1=librosa.load(audio_path_changeLane[i])
    x_changeLane.append(x1)
    sr_changeLane.append(sr1)
    count+=1
print(len(x_changeLane))

77


In [21]:
count=1
x_chalo=[]
sr_chalo=[]
for i in range(0,len(audio_path_chalo)):
    x1,sr1=librosa.load(audio_path_chalo[i])
    x_chalo.append(x1)
    sr_chalo.append(sr1)
    count+=1
print(len(x_chalo))

82


In [22]:
count=1
x_dayainMuro=[]
sr_dayainMuro=[]
for i in range(0,len(audio_path_dayainMuro)):
    x1,sr1=librosa.load(audio_path_dayainMuro[i])
    x_dayainMuro.append(x1)
    sr_dayainMuro.append(sr1)
    count+=1
print(len(x_dayainMuro))

78


In [23]:
count=1
x_turnRight=[]
sr_turnRight=[]
for i in range(0,len(audio_path_turnRight)):
    x1,sr1=librosa.load(audio_path_turnRight[i])
    x_turnRight.append(x1)
    sr_turnRight.append(sr1)
    count+=1
print(len(x_turnRight))

78


In [24]:
count=1
x_turnLeft=[]
sr_turnLeft=[]
for i in range(0,len(audio_path_turnLeft)):
    x1,sr1=librosa.load(audio_path_turnLeft[i])
    x_turnLeft.append(x1)
    sr_turnLeft.append(sr1)
    count+=1
print(len(x_turnLeft))

77


In [25]:
count=1
x_tezChalo=[]
sr_tezChalo=[]
for i in range(0,len(audio_path_tezChalo)):
    x1,sr1=librosa.load(audio_path_tezChalo[i])
    x_tezChalo.append(x1)
    sr_tezChalo.append(sr1)
    count+=1
print(len(x_tezChalo))

75


In [26]:
count=1
x_stop=[]
sr_stop=[]
for i in range(0,len(audio_path_stop)):
    x1,sr1=librosa.load(audio_path_stop[i])
    x_stop.append(x1)
    sr_stop.append(sr1)
    count+=1
print(len(x_stop))

81


In [27]:
count=1
x_start=[]
sr_start=[]
for i in range(0,len(audio_path_start)):
    x1,sr1=librosa.load(audio_path_start[i])
    x_start.append(x1)
    sr_start.append(sr1)
    count+=1
print(len(x_start))

76


In [28]:
count=1
x_speedUp=[]
sr_speedUp=[]
for i in range(0,len(audio_path_speedUp)):
    x1,sr1=librosa.load(audio_path_speedUp[i])
    x_speedUp.append(x1)
    sr_speedUp.append(sr1)
    count+=1
print(len(x_speedUp))

80


In [29]:
count=1
x_speedDown=[]
sr_speedDown=[]
for i in range(0,len(audio_path_speedDown)):
    x1,sr1=librosa.load(audio_path_speedDown[i])
    x_speedDown.append(x1)
    sr_speedDown.append(sr1)
    count+=1
print(len(x_speedDown))

80


In [30]:
count=1
x_rukJao=[]
sr_rukJao=[]
for i in range(0,len(audio_path_rukJao)):
    x1,sr1=librosa.load(audio_path_rukJao[i])
    x_rukJao.append(x1)
    sr_rukJao.append(sr1)
    count+=1
print(len(x_rukJao))

78


<h1>Following is extracting mfccs using audio time series and sampling rate</h1>

In [31]:
import numpy as np
mfcc_ahistaChalo=[]
for i in range(0,len(audio_path_ahistaChalo)):
    mfcc_ahistaChalo.append(librosa.feature.mfcc(x_ahistaChalo[i], n_mfcc=13,sr=sr_ahistaChalo[i]))
print(np.shape(mfcc_ahistaChalo))

(74, 13, 108)


In [32]:
mfcc_bayainMuro=[]
for i in range(0,len(audio_path_bayainMuro)):
    mfcc_bayainMuro.append(librosa.feature.mfcc(x_bayainMuro[i], n_mfcc=13,sr=sr_bayainMuro[i]))
print(np.shape(mfcc_bayainMuro))

(80, 13, 108)


In [33]:
mfcc_chalo=[]
for i in range(0,len(audio_path_chalo)):
    mfcc_chalo.append(librosa.feature.mfcc(x_chalo[i], n_mfcc=13,sr=sr_chalo[i]))
print(np.shape(mfcc_chalo))

(82, 13, 108)


In [34]:
mfcc_changeLane=[]
len(x_changeLane)
for i in range(0,len(audio_path_changeLane)):
    mfcc_changeLane.append(librosa.feature.mfcc(x_changeLane[i], n_mfcc=13,sr=sr_changeLane[i]))
print(np.shape(mfcc_changeLane))

(77, 13, 108)


In [35]:
mfcc_dayainMuro=[]
for i in range(0,len(audio_path_dayainMuro)):
    mfcc_dayainMuro.append(librosa.feature.mfcc(x_dayainMuro[i], n_mfcc=13,sr=sr_dayainMuro[i]))
print(np.shape(mfcc_dayainMuro))

(78, 13, 108)


In [36]:
mfcc_laneBadlo=[]
for i in range(0,len(audio_path_laneBadlo)):
    mfcc_laneBadlo.append(librosa.feature.mfcc(x_laneBadlo[i], n_mfcc=13,sr=sr_laneBadlo[i]))
print(np.shape(mfcc_laneBadlo))

(70, 13, 108)


In [37]:
mfcc_rukJao=[]
for i in range(0,len(audio_path_rukJao)):
    mfcc_rukJao.append(librosa.feature.mfcc(x_rukJao[i], n_mfcc=13,sr=sr_rukJao[i]))
print(np.shape(mfcc_rukJao))

(78, 13, 108)


In [38]:
mfcc_speedDown=[]
for i in range(0,len(audio_path_speedDown)):
    mfcc_speedDown.append(librosa.feature.mfcc(x_speedDown[i], n_mfcc=13,sr=sr_speedDown[i]))
print(np.shape(mfcc_speedDown))

(80, 13, 108)


In [39]:
mfcc_speedUp=[]
for i in range(0,len(audio_path_speedUp)):
    mfcc_speedUp.append(librosa.feature.mfcc(x_speedUp[i], n_mfcc=13,sr=sr_speedUp[i]))
print(np.shape(mfcc_speedUp))

(80, 13, 108)


In [40]:
mfcc_stop=[]
for i in range(0,len(audio_path_stop)):
    mfcc_stop.append(librosa.feature.mfcc(x_stop[i], n_mfcc=13,sr=sr_stop[i]))
print(np.shape(mfcc_stop))

(81, 13, 108)


In [41]:
mfcc_start=[]
for i in range(0,len(audio_path_start)):
    mfcc_start.append(librosa.feature.mfcc(x_start[i], n_mfcc=13,sr=sr_start[i]))
print(np.shape(mfcc_start))

(76, 13, 108)


In [42]:
mfcc_tezChalo=[]
for i in range(0,len(audio_path_tezChalo)):
    mfcc_tezChalo.append(librosa.feature.mfcc(x_tezChalo[i], n_mfcc=13,sr=sr_tezChalo[i]))
print(np.shape(mfcc_tezChalo))

(75, 13, 108)


In [43]:
mfcc_turnLeft=[]
for i in range(0,len(audio_path_turnLeft)):
    mfcc_turnLeft.append(librosa.feature.mfcc(x_turnLeft[i], n_mfcc=13,sr=sr_turnLeft[i]))
print(np.shape(mfcc_turnLeft))

(77, 13, 108)


In [44]:
mfcc_turnRight=[]
for i in range(0,len(audio_path_turnRight)):
    mfcc_turnRight.append(librosa.feature.mfcc(x_turnRight[i], n_mfcc=13,sr=sr_turnRight[i]))
print(np.shape(mfcc_turnRight))

(78, 13, 108)


<h1>Following code combining all mfccs together to make a complete feature data</h1>

In [71]:
import numpy as np
from tensorflow.keras.optimizers import SGD
np.random.seed(1337)
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.layers.recurrent import LSTM
from tensorflow.keras.optimizers import Adam
from keras.layers import Bidirectional
# x_train=np.append(mfcc_ahistaChalo)
x=[]

y=np.zeros(shape=(1086,))

trainCounter=0
for i in range(0,len(mfcc_start)):
        y[trainCounter]=0
        trainCounter+=1
        x.append(mfcc_start[i].T)

for i in range(0,len(mfcc_stop)):
        y[trainCounter]=1
        trainCounter+=1
        x.append(mfcc_stop[i].T)

        
for i in range(0,len(mfcc_changeLane)):
        y[trainCounter]=2
        trainCounter+=1
        x.append(mfcc_changeLane[i].T)        
        

for i in range(0,len(mfcc_turnLeft)):
        y[trainCounter]=3
        trainCounter+=1
        x.append(mfcc_turnLeft[i].T)



for i in range(0,len(mfcc_turnRight)):
        y[trainCounter]=4
        trainCounter+=1
        x.append(mfcc_turnRight[i].T)


for i in range(0,len(mfcc_speedUp)):
        y[trainCounter]=5
        trainCounter+=1
        x.append(mfcc_speedUp[i].T)
        
        

for i in range(0,len(mfcc_speedDown)):
        y[trainCounter]=6
        trainCounter+=1
        x.append(mfcc_speedDown[i].T)
        
        
for i in range(0,len(mfcc_chalo)):
        y[trainCounter]=7
        trainCounter+=1
        x.append(mfcc_chalo[i].T)

        

for i in range(0,len(mfcc_rukJao)):
        y[trainCounter]=8
        trainCounter+=1
        x.append(mfcc_rukJao[i].T)

        
for i in range(0,len(mfcc_laneBadlo)):
        y[trainCounter]=9
        trainCounter+=1
        x.append(mfcc_laneBadlo[i].T)

        
        
for i in range(0,len(mfcc_bayainMuro)):
        y[trainCounter]=10
        trainCounter+=1
        x.append(mfcc_bayainMuro[i].T)

        
        
for i in range(0,len(mfcc_dayainMuro)):
        y[trainCounter]=11
        trainCounter+=1
        x.append(mfcc_dayainMuro[i].T)

        
for i in range(0,len(mfcc_tezChalo)):
        y[trainCounter]=12
        trainCounter+=1
        x.append(mfcc_tezChalo[i].T)


for i in range(0,len(mfcc_ahistaChalo)):
        y[trainCounter]=13
        trainCounter+=1
        x.append(mfcc_ahistaChalo[i].T)

        
        
        
# print(np.shape(x_train))
# print(np.shape(x_test))

print(np.shape(x))
# print(y_train)
# print(y_test)
# print(y_validation)
print("finished")

(1086, 108, 13)
finished


<h1>Following code is splitting data into training and testing data</h1>

In [72]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
nb_classes = 14
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)
print("Finished")

Finished


In [73]:
print(np.shape(X_train))
print(Y_train)

(868, 108, 13)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]]


<h1>Following code is developing a LSTM model which is RNN based Model</h1>
<h1>Two layers along with one dense layer is used to build mode</h1>

In [74]:
modelLSTM = Sequential()
input_shape = (np.array(X_train).shape[1], np.array(X_train).shape[2])
modelLSTM.add(LSTM(units=108, dropout=0.05, recurrent_dropout=0.35, return_sequences=True, input_shape=input_shape))
modelLSTM.add(LSTM(units=32,  dropout=0.05, recurrent_dropout=0.35, return_sequences=False))
modelLSTM.add(Dense(units=Y_train.shape[1], activation="softmax"))
opt = Adam()
modelLSTM.compile(loss="categorical_crossentropy", optimizer=opt, metrics=["accuracy"])
modelLSTM.summary()


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_6 (LSTM)               (None, 108, 108)          52704     
                                                                 
 lstm_7 (LSTM)               (None, 32)                18048     
                                                                 
 dense_3 (Dense)             (None, 14)                462       
                                                                 
Total params: 71,214
Trainable params: 71,214
Non-trainable params: 0
_________________________________________________________________


<h1>Following code is training Lstm model on tarining data set</h1>
<h2>With batch size = 62</h2>
<h2>With epochs = 400</h2>


In [77]:
# print("Training ...")
batch_size = 62   # num of training examples per minibatch
num_epochs = 400
# print(len(x_train))
# print(len(Y_train))
modelLSTM.fit(
    np.array(X_train),
    np.array(Y_train),
    batch_size=batch_size,
    epochs=num_epochs,
)

Epoch 1/400
14/14 [==============================] - 5s 342ms/step - loss: 2.6453 - accuracy: 0.0829
Epoch 2/400
14/14 [==============================] - 7s 465ms/step - loss: 2.6299 - accuracy: 0.0922
Epoch 3/400
14/14 [==============================] - 6s 426ms/step - loss: 2.6184 - accuracy: 0.0922
Epoch 4/400
14/14 [==============================] - 7s 529ms/step - loss: 2.5968 - accuracy: 0.1187
Epoch 5/400
14/14 [==============================] - 7s 470ms/step - loss: 2.5987 - accuracy: 0.1060
Epoch 6/400
14/14 [==============================] - 7s 490ms/step - loss: 2.6043 - accuracy: 0.1071
Epoch 7/400
14/14 [==============================] - 8s 555ms/step - loss: 2.5526 - accuracy: 0.1233
Epoch 8/400
14/14 [==============================] - 8s 558ms/step - loss: 2.5437 - accuracy: 0.1394
Epoch 9/400
14/14 [==============================] - 7s 484ms/step - loss: 2.4848 - accuracy: 0.1382
Epoch 10/400
14/14 [==============================] - 8s 569ms/step - loss: 2.4242 - accura

14/14 [==============================] - 8s 544ms/step - loss: 0.3808 - accuracy: 0.8687
Epoch 161/400
14/14 [==============================] - 8s 539ms/step - loss: 0.3709 - accuracy: 0.8767
Epoch 162/400
14/14 [==============================] - 8s 575ms/step - loss: 0.3669 - accuracy: 0.8675
Epoch 163/400
14/14 [==============================] - 8s 615ms/step - loss: 0.3635 - accuracy: 0.8641
Epoch 164/400
14/14 [==============================] - 8s 588ms/step - loss: 0.3289 - accuracy: 0.8848
Epoch 165/400
14/14 [==============================] - 8s 572ms/step - loss: 0.3815 - accuracy: 0.8687
Epoch 166/400
14/14 [==============================] - 7s 510ms/step - loss: 0.3361 - accuracy: 0.8825
Epoch 167/400
14/14 [==============================] - 8s 598ms/step - loss: 0.3441 - accuracy: 0.8825
Epoch 168/400
14/14 [==============================] - 8s 530ms/step - loss: 0.3389 - accuracy: 0.8836
Epoch 169/400
14/14 [==============================] - 9s 635ms/step - loss: 0.3407 - a

14/14 [==============================] - 9s 632ms/step - loss: 0.1302 - accuracy: 0.9585
Epoch 319/400
14/14 [==============================] - 9s 616ms/step - loss: 0.1024 - accuracy: 0.9747
Epoch 320/400
14/14 [==============================] - 8s 591ms/step - loss: 0.1043 - accuracy: 0.9677
Epoch 321/400
14/14 [==============================] - 9s 643ms/step - loss: 0.0955 - accuracy: 0.9735
Epoch 322/400
14/14 [==============================] - 9s 665ms/step - loss: 0.1053 - accuracy: 0.9700
Epoch 323/400
14/14 [==============================] - 9s 668ms/step - loss: 0.1107 - accuracy: 0.9758
Epoch 324/400
14/14 [==============================] - 9s 655ms/step - loss: 0.0857 - accuracy: 0.9770
Epoch 325/400
14/14 [==============================] - 9s 627ms/step - loss: 0.0747 - accuracy: 0.9827
Epoch 326/400
14/14 [==============================] - 8s 595ms/step - loss: 0.0621 - accuracy: 0.9827
Epoch 327/400
14/14 [==============================] - 9s 657ms/step - loss: 0.0859 - a

In [70]:
print(len(X_train))
print(len(X_test))

760
326


<h1>Testing LSTM model</h1>

In [78]:
print("\nTesting ...")
score, accuracy = modelLSTM.evaluate(
    np.array(X_test), np.array(Y_test), batch_size=batch_size, verbose=1)
print("Test loss:  ", score)
print("Test accuracy:  ", accuracy)


Testing ...
4/4 [==============================] - 1s 48ms/step - loss: 1.3608 - accuracy: 0.6651
Test loss:   1.3607501983642578
Test accuracy:   0.6651375889778137


<h1>Saving LSTM model</h1>

In [69]:
modelFileName="lstm_400_56.h5"
modelLSTM.save("savedModels/"+modelFileName)

<h1>Following code is developing biLstm model, an advances version of LSTM</h1>

In [49]:
modelBiLSTM = Sequential()
input_shape = (np.array(X_train).shape[1], np.array(X_train).shape[2])
modelBiLSTM.add(Bidirectional(LSTM(units=108, dropout=0.05, recurrent_dropout=0.35, return_sequences=True), input_shape=input_shape))
modelBiLSTM.add(Bidirectional(LSTM(units=32,  dropout=0.05, recurrent_dropout=0.35, return_sequences=False)))
modelBiLSTM.add(Dense(units=Y_train.shape[1], activation="softmax"))
opt = Adam()
modelBiLSTM.compile(loss="categorical_crossentropy", optimizer=opt, metrics=["accuracy"])
modelBiLSTM.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bidirectional (Bidirectiona  (None, 108, 216)         105408    
 l)                                                              
                                                                 
 bidirectional_1 (Bidirectio  (None, 64)               63744     
 nal)                                                            
                                                                 
 dense (Dense)               (None, 14)                910       
                                                                 
Total params: 170,062
Trainable params: 170,062
Non-trainable params: 0
_________________________________________________________________


<h1>Following code is training BiLSTM model on training data set</h1>
<h2>With batch size = 56</h2>
<h2>With epochs = 150</h2>

In [110]:
# print("Training ...")
batch_size = 56   # num of training examples per minibatch
num_epochs = 150
print(len(X_train))
print(len(Y_train))
modelBiLSTM.fit(
    np.array(X_train),
    np.array(Y_train),
    batch_size=batch_size,
    epochs=num_epochs,
)

760
760
Epoch 1/150
14/14 [==============================] - 83s 4s/step - loss: 2.6761 - accuracy: 0.0645
Epoch 2/150
14/14 [==============================] - 59s 4s/step - loss: 2.6406 - accuracy: 0.0789
Epoch 3/150
14/14 [==============================] - 66s 5s/step - loss: 2.6146 - accuracy: 0.1079
Epoch 4/150
14/14 [==============================] - 61s 4s/step - loss: 2.5968 - accuracy: 0.1132
Epoch 5/150
14/14 [==============================] - 64s 5s/step - loss: 2.5624 - accuracy: 0.1408
Epoch 6/150
14/14 [==============================] - 63s 5s/step - loss: 2.5318 - accuracy: 0.1487
Epoch 7/150
14/14 [==============================] - 56s 4s/step - loss: 2.4012 - accuracy: 0.2197
Epoch 8/150
14/14 [==============================] - 42s 3s/step - loss: 2.3841 - accuracy: 0.2026
Epoch 9/150
14/14 [==============================] - 41s 3s/step - loss: 2.2899 - accuracy: 0.2171
Epoch 10/150
14/14 [==============================] - 52s 4s/step - loss: 2.2345 - accuracy: 0.2329
E

In [112]:
modelFileName="biLstm_150_56.h5"
modelBiLSTM.save("savedModels/"+modelFileName)

import tensorflow as tf
modelFileName="biLstm_150_56.h5"
modelBiLSTM=tf.keras.models.load_model("savedModels/"+modelFileName)

# numpy.save(file, arr, allow_pickle=True, fix_imports=True)
np.save("savedNumpyArrays/biLSTM_150_56_X_train.npy",np.array(X_train))
np.save("savedNumpyArrays/biLSTM_150_56_Y_train.npy",np.array(Y_train))
np.save("savedNumpyArrays/biLSTM_150_56_X_test.npy",np.array(X_test))
np.save("savedNumpyArrays/biLSTM_150_56_Y_test.npy",np.array(Y_test))



import numpy as np
X_train=np.load("savedNumpyArrays/biLSTM_150_56_X_train.npy")
Y_train=np.load("savedNumpyArrays/biLSTM_150_56_Y_train.npy")
X_test=np.load("savedNumpyArrays/biLSTM_150_56_X_test.npy")
Y_test=np.load("savedNumpyArrays/biLSTM_150_56_Y_test.npy")
print(np.shape(load_X_train))


<h1>Testing BiLSTM model</h1>

In [59]:
batch_size=56
print("\nTesting ...")
score, accuracy = modelBiLSTM.evaluate(
    np.array(X_test), np.array(Y_test), batch_size=batch_size, verbose=1
)
print("Test loss:  ", score)
print("Test accuracy:  ", accuracy)


Testing ...
6/6 [==============================] - 0s 47ms/step - loss: 1.0891 - accuracy: 0.7178
Test loss:   1.0890759229660034
Test accuracy:   0.7177914381027222


modelFileName="biLstm_100_56.h5"
modelBiLSTM.save("savedModels/"+modelFileName)

import tensorflow as tf
modelFileName="biLstm_100_56.h5"
loadBiLstm=tf.keras.models.load_model("savedModels/"+modelFileName)
loadBiLstm.summary()

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=None)
nb_classes = 14
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)


batch_size=56
print("\nTesting ...")
score, accuracy = loadBiLstm.evaluate(
    np.array(X_test), np.array(Y_test), batch_size=batch_size, verbose=1
)
print("Test loss:  ", score)
print("Test accuracy:  ", accuracy)

import tensorflow as tf
modelFileName="lstm_400_56.h5"
loadLstm=tf.keras.models.load_model("savedModels/"+modelFileName)
loadLstm.summary()

batch_size=56
print("\nTesting ...")
score, accuracy = loadLstm.evaluate(
    np.array(X_test), np.array(Y_test), batch_size=batch_size, verbose=1
)
print("Test loss:  ", score)
print("Test accuracy:  ", accuracy)