In [7]:
import librosa
from tensorflow import keras

In [3]:
audioLength=2.5
filesBasicPath='VoiceData/predictionSameLength/'
audioFileLength=[]
audio_path_ahistaChalo=[]
audio_path_bayainMuro=[]
audio_path_chalo=[]
audio_path_changeLane=[]
audio_path_dayainMuro=[]
audio_path_laneBadlo=[]
audio_path_rukJao=[]
audio_path_speedDown=[]
audio_path_speedUp=[]
audio_path_start=[]
audio_path_stop=[]
audio_path_tezChalo=[]
audio_path_turnLeft=[]
audio_path_turnRight=[]
numberOfCommands=12
for i in range(1,numberOfCommands+1):
    if librosa.get_duration(filename=filesBasicPath+str(i)+'/ahista chalo.wav')<=audioLength:
        audio_path_ahistaChalo.append(filesBasicPath+str(i)+'/ahista chalo.wav')
        audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/ahista chalo.wav'))
    if librosa.get_duration(filename=filesBasicPath+str(i)+'/bayain muro.wav')<=audioLength:
        audio_path_bayainMuro.append(filesBasicPath+str(i)+'/bayain muro.wav')
        audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/bayain muro.wav'))
    if librosa.get_duration(filename=filesBasicPath+str(i)+'/chalo.wav')<=2.5:
        audio_path_chalo.append(filesBasicPath+str(i)+'/chalo.wav')
        audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/chalo.wav'))
    if i!=7:
        if librosa.get_duration(filename=filesBasicPath+str(i)+'/dayain muro.wav')<=audioLength:
            audio_path_dayainMuro.append(filesBasicPath+str(i)+'/dayain muro.wav')
            audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/dayain muro.wav'))
    if librosa.get_duration(filename=filesBasicPath+str(i)+'/ruk jao.wav')<=audioLength:
        audio_path_rukJao.append(filesBasicPath+str(i)+'/ruk jao.wav')
        audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/ruk jao.wav'))
    if i!=9:
        if librosa.get_duration(filename=filesBasicPath+str(i)+'/tez chalo.wav')<=audioLength:
            audio_path_tezChalo.append(filesBasicPath+str(i)+'/tez chalo.wav')
            audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/tez chalo.wav'))
    if i!=8:
        if librosa.get_duration(filename=filesBasicPath+str(i)+'/lane badlo.wav')<=audioLength:
            audio_path_laneBadlo.append(filesBasicPath+str(i)+'/lane badlo.wav')
            audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/lane badlo.wav'))
    if librosa.get_duration(filename=filesBasicPath+str(i)+'/change lane.wav')<=audioLength:
        audio_path_changeLane.append(filesBasicPath+str(i)+'/change lane.wav')
        audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/change lane.wav'))
    if librosa.get_duration(filename=filesBasicPath+str(i)+'/speed down.wav')<=audioLength:
        audio_path_speedDown.append(filesBasicPath+str(i)+'/speed down.wav')
        audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/speed down.wav'))
    if librosa.get_duration(filename=filesBasicPath+str(i)+'/speed up.wav')<=audioLength:
        audio_path_speedUp.append(filesBasicPath+str(i)+'/speed up.wav')
        audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/speed up.wav'))
    if librosa.get_duration(filename=filesBasicPath+str(i)+'/start.wav')<=audioLength:
        audio_path_start.append(filesBasicPath+str(i)+'/start.wav')
        audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/start.wav'))
    if librosa.get_duration(filename=filesBasicPath+str(i)+'/stop.wav')<=audioLength:
        audio_path_stop.append(filesBasicPath+str(i)+'/stop.wav')
        audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/stop.wav'))
    if librosa.get_duration(filename=filesBasicPath+str(i)+'/turn left.wav')<=audioLength:
        audio_path_turnLeft.append(filesBasicPath+str(i)+'/turn left.wav')
        audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/turn left.wav'))
    if librosa.get_duration(filename=filesBasicPath+str(i)+'/turn right.wav')<=audioLength:
        audio_path_turnRight.append(filesBasicPath+str(i)+'/turn right.wav')
        audioFileLength.append(librosa.get_duration(filename=filesBasicPath+str(i)+'/turn right.wav'))
print("Loading is completed Done")


Loading is completed Done


In [4]:
count=1
x_ahistaChalo=[]
sr_ahistaChalo=[]
for i in range(0,len(audio_path_ahistaChalo)):
    x1,sr1=librosa.load(audio_path_ahistaChalo[i])
    x_ahistaChalo.append(x1)
    sr_ahistaChalo.append(sr1)
    count+=1
    
print(len(x_ahistaChalo))

12


In [6]:
import numpy as np
mfcc_ahistaChalo=[]
for i in range(0,len(audio_path_ahistaChalo)):
    mfcc_ahistaChalo.append(librosa.feature.mfcc(x_ahistaChalo[i], n_mfcc=13,sr=sr_ahistaChalo[i]).T)
print(np.shape(mfcc_ahistaChalo))

(12, 108, 13)


In [36]:
count=1
x1=0
s1=0
x_bayainMuro=[]
sr_bayainMuro=[]
for i in range(0,len(audio_path_bayainMuro)):
    x1,sr1=librosa.load(audio_path_bayainMuro[i])
    x_bayainMuro.append(x1)
    sr_bayainMuro.append(sr1)
    count+=1
print(len(x_bayainMuro))
mfcc_bayainMuro=[]
for i in range(0,len(audio_path_bayainMuro)):
    mfcc_bayainMuro.append(librosa.feature.mfcc(x_bayainMuro[i], n_mfcc=13,sr=sr_bayainMuro[i]).T)
print(np.shape(mfcc_bayainMuro))

12
(12, 108, 13)


In [45]:
count=1
x_chalo=[]
sr_chalo=[]
for i in range(0,len(audio_path_chalo)):
    x1,sr1=librosa.load(audio_path_chalo[i])
    x_chalo.append(x1)
    sr_chalo.append(sr1)
    count+=1
print(len(x_chalo))
mfcc_chalo=[]
for i in range(0,len(audio_path_chalo)):
    mfcc_chalo.append(librosa.feature.mfcc(x_chalo[i], n_mfcc=13,sr=sr_chalo[i]).T)
print(np.shape(mfcc_chalo))

12
(12, 108, 13)


In [30]:
modelFileName="lstm5_PL_200_370.h5"
modelLSTM = keras.models.load_model("savedModels/"+modelFileName)

In [9]:
modelLSTM.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 108, 108)          52704     
                                                                 
 lstm_1 (LSTM)               (None, 32)                18048     
                                                                 
 dense (Dense)               (None, 14)                462       
                                                                 
Total params: 71,214
Trainable params: 71,214
Non-trainable params: 0
_________________________________________________________________


In [31]:
modelFileName="biLstm5_PL_100_370.h5"
modelBiLSTM = keras.models.load_model("savedModels/"+modelFileName)

In [46]:
y_probLstm=modelLSTM.predict(np.array(mfcc_chalo))
y_classesLstm = y_probLstm.argmax(axis=-1)

In [47]:
print(y_classesLstm)

[7 7 7 7 8 7 7 7 2 8 7 7]


In [48]:
y_probBiLstm=modelBiLSTM.predict(np.array(mfcc_chalo))
y_classesBiLstm = y_probBiLstm.argmax(axis=-1)

In [49]:
print(y_classesBiLstm)

[7 7 7 7 7 7 7 7 2 8 7 7]


In [ ]:
import numpy as np
from tensorflow.keras.optimizers import SGD
np.random.seed(1337)
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.layers.recurrent import LSTM
from tensorflow.keras.optimizers import Adam
# x_train=np.append(mfcc_ahistaChalo)
trainSizeEachCommand=55
validationSizeEachCommand=10
x_train=[]
x_test=[]
x_validation=[]
print(np.shape(mfcc_ahistaChalo))
y_train=np.zeros(shape=(784,))
y_test=np.zeros(shape=(162,))
y_validation=np.zeros(shape=(140,))
print(np.shape(y_train))
print(np.shape(y_test)) 
trainCounter=0
validationCounter=0
testCounter=0
for i in range(0,len(mfcc_start)):
    if i<=trainSizeEachCommand:
        y_train[trainCounter]=0
        trainCounter+=1
        x_train.append(mfcc_start[i].T)
    elif i>trainSizeEachCommand and i<=trainSizeEachCommand+validationSizeEachCommand:
        y_validation[validationCounter]=0
        validationCounter+=1
        x_validation.append(mfcc_start[i].T)
    else:
        y_test[testCounter]=0
        testCounter+=1
        x_test.append(mfcc_start[i].T)

print(y_validation)
print(np.array(y_validation).shape)
for i in range(0,len(mfcc_stop)):
    if i<=trainSizeEachCommand:
        y_train[trainCounter]=1
        trainCounter+=1
        x_train.append(mfcc_stop[i].T)
    elif i>trainSizeEachCommand and i<=trainSizeEachCommand+validationSizeEachCommand:
        y_validation[validationCounter]=1
        validationCounter+=1
        x_validation.append(mfcc_stop[i].T)
    else:
        y_test[testCounter]=1
        testCounter+=1
        x_test.append(mfcc_stop[i].T)

        
print(y_validation)

for i in range(0,len(mfcc_changeLane)):
    if i<=trainSizeEachCommand:
        y_train[trainCounter]=2
        trainCounter+=1
        x_train.append(mfcc_changeLane[i].T)
    elif i>trainSizeEachCommand and i<=trainSizeEachCommand+validationSizeEachCommand:
        y_validation[validationCounter]=2
        validationCounter+=1
        x_validation.append(mfcc_changeLane[i].T)
    else:
        y_test[testCounter]=2
        testCounter+=1
        x_test.append(mfcc_changeLane[i].T)
        
        

for i in range(0,len(mfcc_turnLeft)):
    if i<=trainSizeEachCommand:
        y_train[trainCounter]=3
        trainCounter+=1
        x_train.append(mfcc_turnLeft[i].T)
    elif i>trainSizeEachCommand and i<=trainSizeEachCommand+validationSizeEachCommand:
        y_validation[validationCounter]=3
        validationCounter+=1
        x_validation.append(mfcc_turnLeft[i].T)
    else:
        y_test[testCounter]=3
        testCounter+=1
        x_test.append(mfcc_turnLeft[i].T)



for i in range(0,len(mfcc_turnRight)):
    if i<=trainSizeEachCommand:
        y_train[trainCounter]=4
        trainCounter+=1
        x_train.append(mfcc_turnRight[i].T)
    elif i>trainSizeEachCommand and i<=trainSizeEachCommand+validationSizeEachCommand:
        y_validation[validationCounter]=4
        validationCounter+=1
        x_validation.append(mfcc_turnRight[i].T)
    else:
        y_test[testCounter]=4
        testCounter+=1
        x_test.append(mfcc_turnRight[i].T)
        


for i in range(0,len(mfcc_speedUp)):
    if i<=trainSizeEachCommand:
        y_train[trainCounter]=5
        trainCounter+=1
        x_train.append(mfcc_speedUp[i].T)
    elif i>trainSizeEachCommand and i<=trainSizeEachCommand+validationSizeEachCommand:
        y_validation[validationCounter]=5
        validationCounter+=1
        x_validation.append(mfcc_speedUp[i].T)
    else:
        y_test[testCounter]=5
        testCounter+=1
        x_test.append(mfcc_speedUp[i].T)
        
        

for i in range(0,len(mfcc_speedDown)):
    if i<=trainSizeEachCommand:
        y_train[trainCounter]=6
        trainCounter+=1
        x_train.append(mfcc_speedDown[i].T)
    elif i>trainSizeEachCommand and i<=trainSizeEachCommand+validationSizeEachCommand:
        y_validation[validationCounter]=6
        validationCounter+=1
        x_validation.append(mfcc_speedDown[i].T)
    else:
        y_test[testCounter]=6
        testCounter+=1
        x_test.append(mfcc_speedDown[i].T)
        
        
for i in range(0,len(mfcc_chalo)):
    if i<=trainSizeEachCommand:
        y_train[trainCounter]=7
        trainCounter+=1
        x_train.append(mfcc_chalo[i].T)
    elif i>trainSizeEachCommand and i<=trainSizeEachCommand+validationSizeEachCommand:
        y_validation[validationCounter]=7
        validationCounter+=1
        x_validation.append(mfcc_chalo[i].T)
    else:
        y_test[testCounter]=7
        testCounter+=1
        x_test.append(mfcc_chalo[i].T)
        
        

for i in range(0,len(mfcc_rukJao)):
    if i<=trainSizeEachCommand:
        y_train[trainCounter]=8
        trainCounter+=1
        x_train.append(mfcc_rukJao[i].T)
    elif i>trainSizeEachCommand and i<=trainSizeEachCommand+validationSizeEachCommand:
        y_validation[validationCounter]=8
        validationCounter+=1
        x_validation.append(mfcc_rukJao[i].T)
    else:
        y_test[testCounter]=8
        testCounter+=1
        x_test.append(mfcc_rukJao[i].T)
        
        
for i in range(0,len(mfcc_laneBadlo)):
    if i<=trainSizeEachCommand:
        y_train[trainCounter]=9
        trainCounter+=1
        x_train.append(mfcc_laneBadlo[i].T)
    elif i>trainSizeEachCommand and i<=trainSizeEachCommand+validationSizeEachCommand:
        y_validation[validationCounter]=9
        validationCounter+=1
        x_validation.append(mfcc_laneBadlo[i].T)
    else:
        y_test[testCounter]=9
        testCounter+=1
        x_test.append(mfcc_laneBadlo[i].T)
        
        
for i in range(0,len(mfcc_bayainMuro)):
    if i<=trainSizeEachCommand:
        y_train[trainCounter]=10
        trainCounter+=1
        x_train.append(mfcc_bayainMuro[i].T)
    elif i>trainSizeEachCommand and i<=trainSizeEachCommand+validationSizeEachCommand:
        y_validation[validationCounter]=10
        validationCounter+=1
        x_validation.append(mfcc_bayainMuro[i].T)
    else:
        y_test[testCounter]=10
        testCounter+=1
        x_test.append(mfcc_bayainMuro[i].T)
        
        
        
for i in range(0,len(mfcc_dayainMuro)):
    if i<=trainSizeEachCommand:
        y_train[trainCounter]=11
        trainCounter+=1
        x_train.append(mfcc_dayainMuro[i].T)
    elif i>trainSizeEachCommand and i<=trainSizeEachCommand+validationSizeEachCommand:
        y_validation[validationCounter]=11
        validationCounter+=1
        x_validation.append(mfcc_dayainMuro[i].T)
    else:
        y_test[testCounter]=11
        testCounter+=1
        x_test.append(mfcc_dayainMuro[i].T)
        
        
for i in range(0,len(mfcc_tezChalo)):
    if i<=trainSizeEachCommand:
        y_train[trainCounter]=12
        trainCounter+=1
        x_train.append(mfcc_tezChalo[i].T)
    elif i>trainSizeEachCommand and i<=trainSizeEachCommand+validationSizeEachCommand:
        y_validation[validationCounter]=12
        validationCounter+=1
        x_validation.append(mfcc_tezChalo[i].T)
    else:
        y_test[testCounter]=12
        testCounter+=1
        x_test.append(mfcc_tezChalo[i].T)

        

for i in range(0,len(mfcc_ahistaChalo)):
    if i<=trainSizeEachCommand:
        y_train[trainCounter]=13
        trainCounter+=1
        x_train.append(mfcc_ahistaChalo[i].T)
    elif i>trainSizeEachCommand and i<=trainSizeEachCommand+validationSizeEachCommand:
        y_validation[validationCounter]=13
        validationCounter+=1
        x_validation.append(mfcc_ahistaChalo[i].T)
    else:
        y_test[testCounter]=13
        testCounter+=1
        x_test.append(mfcc_ahistaChalo[i].T)

        
        
        
        
# print(np.shape(x_train))
# print(np.shape(x_test))

print(np.shape(x_train))
print(np.shape(x_test))
print(np.shape(x_validation))
# print(y_train)
# print(y_test)
print(y_validation)


In [128]:
import librosa
import os
import numpy as np
from keras.utils import np_utils

In [143]:
audioLength=2.5
filesBasicPath='VoiceData/predicitonSameLength/'
audioFiles=[]
foldersList=['start','stop','changeLane','turnLeft','turnRight','speedUp','speedDown','chalo','rukJao','laneBadlo','bayainMuro','dayainMuro','tezChalo','ahistaChalo']

foldersListOld=['start','stop','changeLane','turnLeft','turnRight','speedUp','speedDown','chalo','rukJao','laneBadlo','bayainMuro','dayainMuro','tezChalo','ahistaChalo']
outputs=[]
path = os.getcwd()
count=0
for i in range(0,len(foldersList)):
    audioFiles.extend(os.listdir(path+'/'+filesBasicPath+foldersList[i]))
    for j in range(count,len(audioFiles)):
        count+=1
        outputs.append(i)
        audioFiles[j]=filesBasicPath+foldersList[i]+'/'+audioFiles[j]

print(len(audioFiles))
print(len(outputs))
print("File Loading is completed")


101
101
File Loading is completed


In [144]:
timeSeriesValuesList=[]
samplingRateList=[]
for i in range(0,len(audioFiles)):
    timeSeriesValue,samplingRate=librosa.load(audioFiles[i])
    timeSeriesValuesList.append(timeSeriesValue)
    samplingRateList.append(samplingRate)

print("Time series and sampling rate extraction completed")

Time series and sampling rate extraction completed


In [145]:
print(len(samplingRateList))
print(len(timeSeriesValuesList))

101
101


In [146]:
mfccs=[]
for i in range(0,len(audioFiles)):
    mfccs.append(librosa.feature.mfcc(timeSeriesValuesList[i], n_mfcc=13,sr=samplingRateList[i]).T)
    
print("Mfcc extraction completed")

Mfcc extraction completed


In [147]:
print(np.shape(np.array(mfccs)))
print(type(mfccs))
print(type(mfccs[0]))

(101, 108, 13)
<class 'list'>
<class 'numpy.ndarray'>


In [170]:
modelFileName="lstm_400_56.h5"
modelLSTM = keras.models.load_model("savedModels/"+modelFileName)

modelFileName="biLstm_150_56.h5"
modelBiLSTM = keras.models.load_model("savedModels/"+modelFileName)




In [171]:
y_probLstm=modelLSTM.predict(np.array(mfccs))
y_classesLstm = y_probLstm.argmax(axis=-1)

print(y_classesLstm)


[ 1  0  1  7  1  0  1  1  0  8  1  1  1  1  2  2  2  5  2  2  2  2  3  4
  3  3  3  7  4  4  4  0  3  4  7  5  6  6  5  5  5  5  9  6 13  6  5  5
  5 12  7  7  7  1  7  7  5  8  7  8  8 11  5  8  9  9  9  5  9  9  7  8
 10 10 10 10 11 13 10 10  9 11 11 11  3  4 11 12  2  9 12  5  1 12 13 13
 13  3 13 13 13]


In [172]:
y_probBiLstm=modelBiLSTM.predict(np.array(mfccs))
y_classesBiLstm = y_probBiLstm.argmax(axis=-1)

print(y_classesBiLstm)

[ 0  0  2  0  1  0  1  1  0  8  8  7  1  1  2  2  2  6  2  9  2  3  3  3
  3  3  3  3  4  4  4  0  4  3  3  5  9  5  5  5  5  5  9  5 13  6  6  6
  6  7  7  7  7  7  7  5  9  8  8  8  8 11  7  8  9  9  9  9  9  9  9  7
 10 10 10 13 11 10 10  3 11 11 11 11  9 11 11 12 12 11 12 12  7 12 13 13
 13  3 13 13 13]


In [173]:
print(len(y_classesBiLstm))
print(len(outputs))

101
101


In [174]:
lstmCount=0
biLstmCount=0
for i in range (0,len(outputs)):
    print(outputs[i],"   ",y_classesLstm[i],"   ",y_classesBiLstm[i])
    if outputs[i]==y_classesLstm[i]:
        lstmCount+=1
    if outputs[i]==y_classesBiLstm[i]:
        biLstmCount+=1
        
print("Lstm Accuracy: "+str(lstmCount/len(outputs)))
print("BiLstm Accuracy: "+str(biLstmCount/len(outputs)))

0     1     0
0     0     0
0     1     2
0     7     0
0     1     1
0     0     0
1     1     1
1     1     1
1     0     0
1     8     8
1     1     8
1     1     7
1     1     1
1     1     1
2     2     2
2     2     2
2     2     2
2     5     6
2     2     2
2     2     9
2     2     2
3     2     3
3     3     3
3     4     3
3     3     3
3     3     3
3     3     3
3     7     3
4     4     4
4     4     4
4     4     4
4     0     0
4     3     4
4     4     3
4     7     3
5     5     5
5     6     9
5     6     5
5     5     5
5     5     5
5     5     5
5     5     5
6     9     9
6     6     5
6     13     13
6     6     6
6     5     6
6     5     6
6     5     6
7     12     7
7     7     7
7     7     7
7     7     7
7     1     7
7     7     7
7     7     5
7     5     9
8     8     8
8     7     8
8     8     8
8     8     8
8     11     11
8     5     7
8     8     8
9     9     9
9     9     9
9     9     9
9     5     9
9     9     9
9     9     9
9     7     9
9

In [153]:
nb_classes=14
outputClasses = np_utils.to_categorical(outputs, nb_classes)

In [154]:
print(outputClasses)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [155]:
batch_size = 370   # num of training examples per minibatch

print("\nTesting LSTM...")
score, accuracy = modelLSTM.evaluate(
    np.array(mfccs), np.array(outputClasses), batch_size=batch_size, verbose=1)
print("Test loss:  ", score)
print("Test accuracy:  ", accuracy)


Testing LSTM...
1/1 [==============================] - 0s 474ms/step - loss: 0.8865 - accuracy: 0.7822
Test loss:   0.8865411877632141
Test accuracy:   0.7821782231330872


In [156]:
print("\nTesting BiLstm...")
score, accuracy = modelBiLSTM.evaluate(
    np.array(mfccs), np.array(outputClasses), batch_size=batch_size, verbose=1)
print("Test loss:  ", score)
print("Test accuracy:  ", accuracy)


Testing BiLstm...
1/1 [==============================] - 1s 865ms/step - loss: 0.9922 - accuracy: 0.7030
Test loss:   0.9922345876693726
Test accuracy:   0.7029703259468079
